import crypto from 'crypto';
import { v4 as uuidv4 } from 'uuid';
import Database from 'better-sqlite3';
import { getDatabase } from '../db/connection.js';
import {
  Case,
  EvidenceManifestItem,
  SubmissionPacket,
  SubmissionPacketPayload
} from '../domain/types.js';
import { AuditService } from './audit-service.js';

export class SubmissionPacketService {
  private auditService: AuditService;

  constructor(private db: Database.Database = getDatabase()) {
    this.auditService = new AuditService(this.db);
  }

  /**
   * Generates a deterministic, dry-run submission packet for a case
   */
  public generatePacket(
    caseData: Case,
    generatedBy: string
  ): SubmissionPacket {
    // 1. Fetch available evidence items for manifest
    const evidenceRows = this.db.prepare(`
      SELECT id, safe_display_name, sha256, byte_size, mime_type, created_at, storage_key
      FROM evidence_items
      WHERE case_id = ? AND organization_id = ? AND status = 'available'
      ORDER BY created_at ASC
    `).all(caseData.id, caseData.organization_id) as Array<{
      id: string;
      safe_display_name: string;
      sha256: string;
      byte_size: number;
      mime_type: string;
      created_at: string;
      storage_key: string;
    }>;

    const manifestItems: EvidenceManifestItem[] = evidenceRows.map((row) => ({
      evidence_id: row.id,
      safe_display_name: row.safe_display_name.replace(/[^a-zA-Z0-9._-]/g, '_'),
      sha256: row.sha256,
      byte_size: row.byte_size,
      mime_type: row.mime_type,
      captured_at: row.created_at,
      storage_key_obscured: `sha256:${row.sha256.substring(0, 16)}...`
    }));

    const totalBytes = evidenceRows.reduce((acc, row) => acc + row.byte_size, 0);

    let statutoryBasisList: string[] = [];
    let legalGroundsList: string[] = [];
    try {
      statutoryBasisList = JSON.parse(caseData.statutory_basis || '[]');
      legalGroundsList = JSON.parse(caseData.selected_legal_grounds || '[]');
    } catch {
      // ignore
    }

    const payload: SubmissionPacketPayload = {
      packet_version: 1,
      mode: 'DRY_RUN_ONLY_SIMULATION',
      generated_at: new Date().toISOString(),
      organization_id: caseData.organization_id,
      case_id: caseData.id,
      case_number: caseData.case_number,
      title: caseData.title,
      affected_party: {
        target_entity: caseData.target_entity,
        target_entity_type: caseData.target_entity_type || 'individual_professional',
        reported_by_name: caseData.reported_by_name || undefined,
        reported_by_email: caseData.reported_by_email,
        jurisdiction: caseData.affected_jurisdiction || 'IN-National'
      },
      incident_details: {
        hosting_platform: caseData.hosting_platform,
        contested_url: caseData.contested_url,
        category: caseData.category,
        suspected_synthetic_media_type: caseData.suspected_synthetic_media_type || 'none',
        impersonation_method: caseData.impersonation_method || 'profile_cloning',
        harm_type: caseData.harm_type || 'reputational',
        discovered_at: caseData.discovered_at || undefined,
        factual_basis: caseData.factual_basis || undefined
      },
      statutory_grounds: {
        statutory_basis: statutoryBasisList,
        selected_legal_grounds: legalGroundsList,
        has_court_or_government_order: Boolean(caseData.has_court_or_government_order),
        court_or_government_order_details: caseData.court_or_government_order_details || undefined,
        operational_basis: caseData.involves_intimate_imagery
          ? 'IT Rules 2021 Rule 3(2)(b) (24h Window)'
          : 'IT Rules 2021 Rule 3(1)(b) (72h Window)'
      },
      evidence_manifest: manifestItems,
      chain_of_custody_summary: {
        item_count: manifestItems.length,
        total_bytes: totalBytes,
        custody_verified: true
      },
      requested_action:
        'Immediate disabling of access, preservation of account records, and removal under Information Technology Rules, 2021.',
      reporter_declaration:
        'I hereby solemnly state and declare under penalty of perjury that the statements made herein are true and correct to the best of my knowledge, and that the identified digital material constitutes unauthorized impersonation.',
      approval_status: caseData.approval_status || 'ready_for_submission',
      internal_warnings: [
        'SIMULATION ONLY: This packet was generated by Digital Impersonation Response Desk in dry-run simulation mode.',
        'No external network transmission or automated platform takedown request has been dispatched.'
      ]
    };

    // Deterministic canonical JSON
    const packetJson = JSON.stringify(payload, null, 2);
    const packetHash = crypto.createHash('sha256').update(packetJson).digest('hex');

    // Generate Markdown Notice
    const packetMarkdown = this.generateMarkdownNotice(payload, packetHash);

    const packetId = uuidv4();
    this.db.prepare(`
      INSERT INTO submission_packets (
        id, case_id, organization_id, packet_version, status,
        packet_hash, packet_json, packet_markdown, evidence_manifest_json,
        generated_by, created_at
      ) VALUES (?, ?, ?, 1, 'dry_run_generated', ?, ?, ?, ?, ?, ?)
    `).run(
      packetId,
      caseData.id,
      caseData.organization_id,
      packetHash,
      packetJson,
      packetMarkdown,
      JSON.stringify(manifestItems),
      generatedBy,
      payload.generated_at
    );

    return {
      id: packetId,
      case_id: caseData.id,
      organization_id: caseData.organization_id,
      packet_version: 1,
      status: 'dry_run_generated',
      packet_hash: packetHash,
      packet_json: packetJson,
      packet_markdown: packetMarkdown,
      evidence_manifest_json: JSON.stringify(manifestItems),
      generated_by: generatedBy,
      created_at: payload.generated_at
    };
  }

  /**
   * Generates a formal legal takedown notice in Markdown format
   */
  private generateMarkdownNotice(payload: SubmissionPacketPayload, packetHash: string): string {
    const lines: string[] = [];

    lines.push('# STATUTORY GRIEVANCE AND INTERMEDIARY TAKEDOWN NOTICE');
    lines.push('*(SIMULATED PILOT SUBMISSION PACKET — DRY-RUN ONLY)*\n');
    lines.push(`**Notice Identifier:** \`${payload.case_number}\``);
    lines.push(`**Packet Integrity Digest (SHA-256):** \`${packetHash}\``);
    lines.push(`**Generated At:** ${payload.generated_at}`);
    lines.push(`**Applicable Jurisdiction:** ${payload.affected_party.jurisdiction}\n`);

    lines.push('---');
    lines.push('### TO: Resident Grievance Officer / Legal Operations');
    lines.push(`**Intermediary / Platform:** ${payload.incident_details.hosting_platform}`);
    lines.push('**Statutory Reference:** Section 79(3)(b) Information Technology Act, 2000 read with Rules 3(1)(b) & 3(2)(b) of the IT (Intermediary Guidelines and Digital Media Ethics Code) Rules, 2021\n');

    lines.push('### 1. AFFECTED PARTY & REPORTER IDENTIFICATION');
    lines.push(`- **Target Entity / Individual:** ${payload.affected_party.target_entity} (${payload.affected_party.target_entity_type})`);
    if (payload.affected_party.reported_by_name) {
      lines.push(`- **Authorized Reporter Name:** ${payload.affected_party.reported_by_name}`);
    }
    lines.push(`- **Contact Email:** ${payload.affected_party.reported_by_email}\n`);

    lines.push('### 2. CONTESTED DIGITAL ASSET & INCIDENT PARTICULARS');
    lines.push(`- **Contested Location URL:** ${payload.incident_details.contested_url}`);
    lines.push(`- **Incident Category:** ${payload.incident_details.category}`);
    lines.push(`- **Synthetic Media Involved:** ${payload.incident_details.suspected_synthetic_media_type}`);
    lines.push(`- **Impersonation Method:** ${payload.incident_details.impersonation_method}`);
    lines.push(`- **Harm Classification:** ${payload.incident_details.harm_type}`);
    if (payload.incident_details.factual_basis) {
      lines.push(`- **Factual Substantiation:** ${payload.incident_details.factual_basis}`);
    }
    lines.push('');

    lines.push('### 3. STATUTORY AND LEGAL GROUNDS');
    payload.statutory_grounds.statutory_basis.forEach((basis) => {
      lines.push(`- ${basis}`);
    });
    payload.statutory_grounds.selected_legal_grounds.forEach((ground) => {
      lines.push(`- Legal Ground: ${ground}`);
    });
    if (payload.statutory_grounds.has_court_or_government_order) {
      lines.push(`- **Judicial / Government Order Notice:** ${payload.statutory_grounds.court_or_government_order_details}`);
    }
    lines.push('');

    lines.push('### 4. CHAIN OF CUSTODY EVIDENCE MANIFEST');
    lines.push(`*Total Preserved Assets: ${payload.chain_of_custody_summary.item_count} (${payload.chain_of_custody_summary.total_bytes} bytes)*\n`);
    lines.push('| Safe File Name | MIME Type | Byte Size | SHA-256 Digest | Captured At |');
    lines.push('|---|---|---|---|---|');
    payload.evidence_manifest.forEach((item) => {
      lines.push(`| \`${item.safe_display_name}\` | ${item.mime_type} | ${item.byte_size} | \`${item.sha256}\` | ${item.captured_at} |`);
    });
    lines.push('');

    lines.push('### 5. REQUESTED RELIEF & TIMEFRAME');
    lines.push(payload.requested_action);
    lines.push(`Statutory compliance window: **${payload.statutory_grounds.operational_basis}**\n`);

    lines.push('### 6. FORMAL DECLARATION');
    lines.push(`> "${payload.reporter_declaration}"\n`);

    lines.push('---');
    lines.push('**SYSTEM SAFETY DISCLAIMER:**');
    payload.internal_warnings.forEach((w) => lines.push(`* ${w}`));

    return lines.join('\n');
  }

  /**
   * Simulates dispatching the submission packet (dry-run record only)
   */
  public simulateSubmission(
    caseId: string,
    organizationId: string,
    actorUserId: string,
    actorEmail: string
  ): { packet: SubmissionPacket; simulatedAt: string } {
    const packetRow = this.db.prepare(`
      SELECT * FROM submission_packets
      WHERE case_id = ? AND organization_id = ?
      ORDER BY created_at DESC
      LIMIT 1
    `).get(caseId, organizationId) as any;

    if (!packetRow) {
      throw new Error(`No generated submission packet found for case ${caseId}`);
    }

    const simulatedAt = new Date().toISOString();

    this.db.prepare(`
      UPDATE submission_packets
      SET status = 'simulated', simulated_at = ?
      WHERE id = ?
    `).run(simulatedAt, packetRow.id);

    // Update case approval status to submission_simulated
    this.db.prepare(`
      UPDATE cases
      SET approval_status = 'submission_simulated', updated_at = ?
      WHERE id = ? AND organization_id = ?
    `).run(simulatedAt, caseId, organizationId);

    this.auditService.record({
      organization_id: organizationId,
      actor_user_id: actorUserId,
      actor_email: actorEmail,
      action: 'case.submission_simulated',
      resource_type: 'case',
      resource_id: caseId,
      details: {
        packet_id: packetRow.id,
        packet_hash: packetRow.packet_hash,
        simulated_at: simulatedAt,
        mode: 'DRY_RUN_ONLY_SIMULATION'
      }
    });

    return {
      packet: {
        id: packetRow.id,
        case_id: packetRow.case_id,
        organization_id: packetRow.organization_id,
        packet_version: packetRow.packet_version,
        status: 'simulated',
        packet_hash: packetRow.packet_hash,
        packet_json: packetRow.packet_json,
        packet_markdown: packetRow.packet_markdown,
        evidence_manifest_json: packetRow.evidence_manifest_json,
        generated_by: packetRow.generated_by,
        approved_by: packetRow.approved_by,
        simulated_at: simulatedAt,
        created_at: packetRow.created_at
      },
      simulatedAt
    };
  }

  /**
   * Retrieves the latest submission packet for a case
   */
  public getLatestPacket(caseId: string, organizationId: string): SubmissionPacket | null {
    const row = this.db.prepare(`
      SELECT * FROM submission_packets
      WHERE case_id = ? AND organization_id = ?
      ORDER BY created_at DESC
      LIMIT 1
    `).get(caseId, organizationId) as any;

    if (!row) return null;

    return {
      id: row.id,
      case_id: row.case_id,
      organization_id: row.organization_id,
      packet_version: row.packet_version,
      status: row.status,
      packet_hash: row.packet_hash,
      packet_json: row.packet_json,
      packet_markdown: row.packet_markdown,
      evidence_manifest_json: row.evidence_manifest_json,
      generated_by: row.generated_by,
      approved_by: row.approved_by,
      simulated_at: row.simulated_at,
      created_at: row.created_at
    };
  }
}
